const app=document.getElementById('app');const title=document.getElementById('title');let center=null;
const fallbackProjects=[{name:'FUSE Iraq',type:'Food / Delivery',status:'تشغيل',progress:78},{name:'Suqly AI',type:'AI SaaS',status:'تشغيل',progress:88},{name:'Fancy Hub',type:'E-commerce',status:'تطوير',progress:64},{name:'Jardak AI',type:'Retail AI',status:'تطوير',progress:72},{name:'JAZAL',type:'Audio / Media',status:'تشغيل',progress:81}];
async function loadCenter(){try{const r=await fetch('/api/command-center');if(!r.ok)throw 0;center=await r.json()}catch(e){center=null}}
function projects(){return center?.portfolio||fallbackProjects}function opps(){return center?.opportunities||[]}
function home(){title.textContent='مركز القيادة';const ps=projects(),os=opps(),today=center?.today;app.innerHTML=`<div class="card"><p class="eyebrow">قرار JODA اليوم</p><h2>${today?.primaryDecision||'حلل محفظتك وحدد أعلى خطوة ربحية قابلة للتنفيذ.'}</h2><p class="muted">${today?.why||'المركز يستخدم بيانات المشاريع والفرص والمهام لتحديد الأولوية.'}</p></div><div class="grid"><div class="card metric"><small>المشاريع</small><strong>${ps.length}</strong><em>مراقبة</em></div><div class="card metric"><small>الفرص</small><strong>${os.length}</strong><em>قيد التقييم</em></div><div class="card metric"><small>المهام</small><strong>${center?.tasks?.length||0}</strong><em>Execution Queue</em></div><div class="card metric"><small>حالة الوكيل</small><strong>●</strong><em>متصل</em></div></div><div class="two section"><div class="card"><div class="section-title"><h3>المحفظة الحالية</h3><span class="muted">Live context</span></div>${ps.map(p=>`<div class="project"><div><b>${p.name||p.project}</b><small class="muted"> · ${p.type||''}</small><div class="bar"><i style="width:${p.progress||0}%"></i></div></div><span class="tag">${p.status||p.activity||'مراقبة'}</span></div>`).join('')}</div><div class="card"><div class="section-title"><h3>الفرص</h3><span class="muted">JODA</span></div>${os.slice(0,5).map(o=>`<div class="opportunity"><div><b>${o.name}</b><small class="muted">${o.type||''}</small></div><span class="score">${o.score||''}</span></div>`).join('')}</div></div>`}
function portfolio(){title.textContent='المحفظة';app.innerHTML=`<div class="card"><div class="section-title"><h3>كل المشاريع</h3><button class="primary" onclick="openModal()">+ اسأل JODA</button></div>${projects().map(p=>`<div class="project"><div><b>${p.name||p.project}</b><div class="muted">${p.type||''} ${p.progress?'· تقدم '+p.progress+'%':''}</div></div><span class="tag">${p.status||p.activity||'مراقبة'}</span></div>`).join('')}</div>`}
function opportunities(){title.textContent='محرك الفرص';app.innerHTML=`<div class="card"><div class="section-title"><div><h3>فرص يقترحها JODA</h3><small class="muted">مرتبة حسب القيمة والجاهزية والمخاطر</small></div><button class="primary" onclick="openModal()">حلل فرصة ✦</button></div>${opps().map(o=>`<div class="opportunity"><div><b>${o.name}</b><small class="muted">${o.type||''}</small></div><span class="score">${o.score||''}</span></div>`).join('')}</div>`}
function builder(){title.textContent='بناء شركة';app.innerHTML=`<div class="card"><p class="eyebrow">COMPANY BUILDER</p><h2>حوّل فكرة إلى شركة قابلة للتنفيذ</h2><p class="muted">اطلب من JODA بناء المشكلة، العميل، العرض، الإيرادات، MVP، التحقق، النمو وخيارات الخروج.</p><button class="primary" onclick="ask('ابني لي شركة جديدة قابلة للربح في العراق، اختبر الفكرة أولاً ثم اعطني MVP والتسعير وخطة أول 10 عملاء')">ابدأ بناء شركة ✦</button></div>`}
function growth(){title.textContent='النمو';app.innerHTML=`<div class="card"><h3>Growth Command</h3><p class="muted">اطلب من JODA اختيار أسرع تجربة نمو قابلة للقياس.</p><button class="primary" onclick="ask('حلل محفظتي واختر أسرع تجربة نمو تحقق إيراداً خلال 14 يوم')">شغّل Growth Agent ✦</button></div>`}
function research(){title.textContent='الأبحاث';app.innerHTML=`<div class="card"><p class="eyebrow">RESEARCH ENGINE</p><h2>مركز أبحاث السوق</h2><p class="muted">اكتب طلب البحث مباشرة للوكيل.</p><button class="primary" onclick="openModal()">اطلب بحثاً ✦</button></div>`}
async function plans(){title.textContent='خطط التنفيذ';const goal=prompt('شنو الهدف اللي تريد JODA يحوله لخطة؟','جهز المشروع للإطلاق');if(!goal){home();return}app.innerHTML='<div class="card"><p>JODA يبني الخطة...</p></div>';try{const r=await fetch('/api/orchestrate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({goal})});const d=await r.json();const p=d.plan;app.innerHTML=`<div class="card"><div class="section-title"><div><p class="eyebrow">EXECUTION PLAN</p><h2>${p.goal}</h2></div><span class="tag">${p.id}</span></div><div class="plan">${p.tasks.map(t=>`<div class="task"><div><b>${t.title}</b><small class="muted">${t.id} · ${t.priority} · يعتمد على: ${t.dependsOn.join(', ')||'لا يوجد'}</small></div><span class="tag">${t.status}</span></div>`).join('')}</div><p class="muted">${p.policy}</p></div>`}catch(e){app.innerHTML='<div class="card">تعذر إنشاء الخطة حالياً.</div>'}}
const views={home,portfolio,opportunities,builder,growth,research,plans};document.querySelectorAll('.nav').forEach(b=>b.onclick=async()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');await loadCenter();views[b.dataset.view]()});
function openModal(initial=''){document.getElementById('modal').classList.remove('hidden');document.getElementById('prompt').value=initial;document.getElementById('prompt').focus()}function closeModal(){document.getElementById('modal').classList.add('hidden')}function ask(x){openModal(x)}document.getElementById('agentBtn').onclick=()=>openModal();document.getElementById('close').onclick=closeModal;document.getElementById('refresh').onclick=async()=>{await loadCenter();views[document.querySelector('.nav.active').dataset.view]()};document.getElementById('run').onclick=async()=>{const p=document.getElementById('prompt').value.trim(),a=document.getElementById('answer');if(!p){a.textContent='اكتب طلبك أولاً.';return}a.textContent='JODA يحلل الطلب...';try{const r=await fetch('/api/command',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message:p})});const d=await r.json();a.innerHTML='<b>النية:</b> '+d.intent+'<br><br><b>JODA:</b> '+(typeof d.answer==='string'?d.answer:JSON.stringify(d.answer,null,2))+'<br><br><small>'+d.nextStep+'</small>'}catch(e){a.textContent='تعذر الاتصال بالوكيل حالياً. جرّب تحديث الصفحة.'}};(async()=>{await loadCenter();home()})();
