const projects=[{name:'FUSE Iraq',type:'Food / Delivery',status:'تشغيل',progress:78},{name:'Suqly AI',type:'AI SaaS',status:'تشغيل',progress:88},{name:'Fancy Hub',type:'E-commerce',status:'تطوير',progress:64},{name:'Jardak AI',type:'Retail AI',status:'تطوير',progress:72},{name:'JAZAL',type:'Audio / Media',status:'تشغيل',progress:81}];
const opportunities=[['وكيل مبيعات للشركات العراقية','B2B AI','87%'],['منصة إدارة المطاعم الذكية','FoodTech','82%'],['AI Inventory للعراق والخليج','Retail AI','79%'],['منصة SaaS للفواتير والديون','FinTech','76%']];
const app=document.getElementById('app'); const title=document.getElementById('title');
function home(){title.textContent='مركز القيادة';app.innerHTML=`<div class="grid"><div class="card metric"><small>المشاريع</small><strong>5</strong><em>+2 هذا العام</em></div><div class="card metric"><small>قيمة المحفظة</small><strong>$—</strong><em>تحتاج بيانات مالية</em></div><div class="card metric"><small>فرص مكتشفة</small><strong>18</strong><em>4 فرص عالية</em></div><div class="card metric"><small>مهام الوكيل</small><strong>12</strong><em>3 تحتاج موافقة</em></div></div><div class="two section"><div class="card"><div class="section-title"><h3>المحفظة الحالية</h3><span class="muted">آخر حالة</span></div>${projects.map(p=>`<div class="project"><div><b>${p.name}</b><small class="muted"> · ${p.type}</small><div class="bar"><i style="width:${p.progress}%"></i></div></div><span class="tag">${p.status}</span></div>`).join('')}</div><div class="card"><div class="section-title"><h3>أفضل الفرص</h3><span class="muted">AI Score</span></div>${opportunities.map(o=>`<div class="opportunity"><div><b>${o[0]}</b><small class="muted">${o[1]}</small></div><span class="score">${o[2]}</span></div>`).join('')}</div></div>`}
function portfolio(){title.textContent='المحفظة';app.innerHTML=`<div class="card"><div class="section-title"><h3>كل المشاريع</h3><button class="primary" onclick="openModal()">+ مشروع جديد</button></div>${projects.map(p=>`<div class="project"><div><b>${p.name}</b><div class="muted">${p.type} · تقدم ${p.progress}%</div></div><span class="tag">${p.status}</span></div>`).join('')}</div>`}
function opportunities(){title.textContent='محرك الفرص';app.innerHTML=`<div class="card"><div class="section-title"><div><h3>فرص يقترحها JODA</h3><small class="muted">مرتبة حسب الطلب، المنافسة، رأس المال وسرعة الوصول للسوق</small></div><button class="primary" onclick="openModal()">حلل السوق ✦</button></div>${opportunities.map((o,i)=>`<div class="opportunity"><div><b>${o[0]}</b><small class="muted">${o[1]} · ${i<2?'فرصة عالية':'فرصة واعدة'}</small></div><span class="score">${o[2]}</span></div>`).join('')}</div>`}
function builder(){title.textContent='بناء شركة';app.innerHTML=`<div class="card"><p class="eyebrow">COMPANY BUILDER</p><h2>حوّل فكرة إلى شركة قابلة للتنفيذ</h2><p class="muted">JODA يبني الاسم، المشكلة، العرض، نموذج الإيرادات، MVP، خطة التسويق، مؤشرات النجاح وخطة الخروج.</p><button class="primary" onclick="openModal()">ابدأ بناء شركة ✦</button></div>`}
function growth(){title.textContent='النمو';app.innerHTML=`<div class="grid"><div class="card metric"><small>أهداف نشطة</small><strong>9</strong></div><div class="card metric"><small>قيد التنفيذ</small><strong>6</strong></div><div class="card metric"><small>مكتملة</small><strong>21</strong></div><div class="card metric"><small>تحتاج قرار</small><strong>3</strong></div></div><div class="card section"><h3>قاعدة JODA للنمو</h3><p class="muted">راقب الإيرادات، اكتساب العملاء، الاحتفاظ، تكلفة الاكتساب، الهامش، سرعة التنفيذ، ومخاطر كل شركة.</p></div>`}
function research(){title.textContent='الأبحاث';app.innerHTML=`<div class="card"><p class="eyebrow">RESEARCH ENGINE</p><h2>مركز أبحاث السوق</h2><p class="muted">هنا سيجمع الوكيل لاحقاً بيانات السوق والمنافسين والأسعار والطلب، ثم يحولها إلى قرارات قابلة للتنفيذ.</p><button class="primary" onclick="openModal()">اطلب بحثاً ✦</button></div>`}
const views={home,portfolio,opportunities,builder,growth,research};document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');views[b.dataset.view]()});
function openModal(){document.getElementById('modal').classList.remove('hidden');document.getElementById('prompt').focus()}function closeModal(){document.getElementById('modal').classList.add('hidden')}document.getElementById('agentBtn').onclick=openModal;document.getElementById('close').onclick=closeModal;document.getElementById('refresh').onclick=()=>views[document.querySelector('.nav.active').dataset.view]();document.getElementById('run').onclick=async()=>{const p=document.getElementById('prompt').value.trim();const a=document.getElementById('answer');if(!p){a.textContent='اكتب طلبك أولاً.';return}a.textContent='JODA يحلل الطلب ويجهز خطة...';try{const r=await fetch('/api/agent',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({prompt:p})});if(r.ok){const d=await r.json();a.textContent=d.answer||'تم التحليل.'}else throw new Error()}catch(e){a.innerHTML='<b>وضع التخطيط المحلي:</b><br>سأحوّل طلبك إلى 1) الهدف 2) السوق 3) الميزة 4) نموذج الإيرادات 5) MVP 6) خطة إطلاق 7) المخاطر 8) قرار التنفيذ. الربط مع مزود AI الخارجي يحتاج مفتاح API في Vercel.'}};home();
